name: tlc
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/berkobob/tradelog-command-line

environment:
    sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0

dependencies:
    args: ^2.3.1
    dcli: ^1.30.2
    http: ^0.13.4
    interact: ^2.1.1
    intl: ^0.17.0
    yaml: ^3.1.1
